development:
  adapter: postgresql
  database: doug_teixeira_dev
  host: localhost
  username: Doug
  password: ENV['DEV_PASSWORD']
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: doug_teixeira_test
  host: localhost
  username: Doug
  password: ENV['DEV_PASSWORD']
  
production:
  adapter: postgresql
  database: doug_teixeira_production
  host: localhost
  username: Doug
  password: ENV['DEV_PASSWORD']
  pool: 5
  timeout: 5000